package aatree;

import org.junit.Test;

import common.Utilities;
import gov.nasa.jpf.util.test.TestJPF;

public class AATree_remove1 extends TestJPF {

	@Test
	public void test_remove1() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode right_18 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_71 = new aatree.AATree.AANode();
		aatree.AATree.AANode left_17 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_13 = obj.nullNode;
		aatree.AATree.AANode c_14 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_92 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_93 = t_3;
		aatree.AATree.AANode this_deletedNode_94 = t_3;
		aatree.AATree.AANode t_5 = right_18;
		aatree.AATree.AANode this_lastNode_95 = t_5;
		aatree.AATree.AANode this_deletedNode_96 = t_5;
		aatree.AATree.AANode t_7 = right_71;
		aatree.AATree.AANode this_lastNode_97 = t_7;
		aatree.AATree.AANode this_lastNode_98 = t_7;
		aatree.AATree.AANode this_nullNode_320 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_324 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_327 = obj.nullNode;
		aatree.AATree.AANode left_70 = this_nullNode_320;
		aatree.AATree.AANode left_84 = this_nullNode_324;
		aatree.AATree.AANode right_85 = this_nullNode_327;
		aatree.AATree.AANode left_453 = obj.nullNode;
		aatree.AATree.AANode right_452 = obj.nullNode;
		int x = 1;
		int level_19 = 2;
		int x_1 = 1;
		int level1_317 = 1;
		int x_4 = 1;
		int x_2 = 1;
		int minE_20 = -3;
		int level1_321 = 1;
		int element_318 = -1;
		int element_69 = 0;
		int x_6 = 1;
		int element_319 = 0;
		int element_316 = -1;
		int level1_21 = 1;
		int maxE_22 = 2;
		int element_83 = 1;
		int d_15 = 0;
		int element_323 = 1;
		int element_451 = -2;
		int a_12 = 0;
		int element_16 = -1;
		int element_322 = 0;
		int element_325 = 1;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_16;
		obj.root.left = left_17;
		obj.root.right = right_18;
		obj.root.level = level_19;
		right_18.element = element_69;
		right_18.left = left_70;
		right_18.right = right_71;
		right_18.level = level1_317;
		right_71.element = element_83;
		right_71.left = left_84;
		right_71.right = right_85;
		right_71.level = level1_321;
		left_17.element = element_451;
		left_17.left = left_453;
		left_17.right = right_452;
		left_17.level = level1_21;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove2() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode left_17 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_84 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_18 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_13 = obj.nullNode;
		aatree.AATree.AANode c_14 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_102 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_103 = t_3;
		aatree.AATree.AANode t_5 = left_17;
		aatree.AATree.AANode this_lastNode_104 = t_5;
		aatree.AATree.AANode this_deletedNode_105 = t_5;
		aatree.AATree.AANode t_7 = right_84;
		aatree.AATree.AANode this_lastNode_106 = t_7;
		aatree.AATree.AANode this_lastNode_107 = t_7;
		aatree.AATree.AANode this_nullNode_319 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_323 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_327 = obj.nullNode;
		aatree.AATree.AANode left_83 = this_nullNode_319;
		aatree.AATree.AANode left_95 = this_nullNode_323;
		aatree.AATree.AANode right_96 = this_nullNode_327;
		aatree.AATree.AANode left_451 = obj.nullNode;
		aatree.AATree.AANode right_450 = obj.nullNode;
		int level_19 = 2;
		int x_1 = -2;
		int level1_317 = 1;
		int element_94 = -1;
		int x_4 = -2;
		int element_449 = 1;
		int x_2 = -2;
		int minE_20 = -3;
		int element_321 = -2;
		int element_318 = -2;
		int x_6 = -2;
		int element_316 = 0;
		int level1_21 = 1;
		int level1_320 = 1;
		int maxE_22 = 2;
		int d_15 = 0;
		int element_82 = -2;
		int a_12 = 0;
		int element_16 = 0;
		int element_322 = -1;
		int element_324 = -1;
		int x = -2;
		int element_325 = 0;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_16;
		obj.root.left = left_17;
		obj.root.right = right_18;
		obj.root.level = level_19;
		left_17.element = element_82;
		left_17.left = left_83;
		left_17.right = right_84;
		left_17.level = level1_317;
		right_84.element = element_94;
		right_84.left = left_95;
		right_84.right = right_96;
		right_84.level = level1_320;
		right_18.element = element_449;
		right_18.left = left_451;
		right_18.right = right_450;
		right_18.level = level1_21;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove3() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode right_33 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_28 = obj.nullNode;
		aatree.AATree.AANode c_29 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_50 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_51 = t_3;
		aatree.AATree.AANode this_deletedNode_52 = t_3;
		aatree.AATree.AANode t_5 = right_33;
		aatree.AATree.AANode this_lastNode_53 = t_5;
		aatree.AATree.AANode this_deletedNode_54 = t_5;
		aatree.AATree.AANode t_7 = obj.nullNode;
		aatree.AATree.AANode right_55 = t_7;
		aatree.AATree.AANode this_nullNode_320 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_323 = obj.nullNode;
		aatree.AATree.AANode left_32 = obj.nullNode;
		aatree.AATree.AANode left_44 = this_nullNode_320;
		aatree.AATree.AANode right_45 = this_nullNode_323;
		int x_1 = 1;
		int element_31 = -1;
		int level_317 = 1;
		int maxE_37 = 1;
		int element_43 = 0;
		int x_4 = 1;
		int x_2 = 1;
		int a_27 = 0;
		int d_30 = 0;
		int level_34 = 1;
		int element_321 = 0;
		int element_318 = -1;
		int x_6 = 1;
		int x = 1;
		int element_316 = -1;
		int element_319 = 0;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_31;
		obj.root.left = left_32;
		obj.root.right = right_33;
		obj.root.level = level_34;
		right_33.element = element_43;
		right_33.left = left_44;
		right_33.right = right_45;
		right_33.level = level_317;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove4() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode right_19 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_71 = new aatree.AATree.AANode();
		aatree.AATree.AANode left_18 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_14 = obj.nullNode;
		aatree.AATree.AANode c_15 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_91 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_92 = t_3;
		aatree.AATree.AANode this_deletedNode_93 = t_3;
		aatree.AATree.AANode t_5 = right_19;
		aatree.AATree.AANode this_lastNode_94 = t_5;
		aatree.AATree.AANode this_deletedNode_95 = t_5;
		aatree.AATree.AANode t_7 = right_71;
		aatree.AATree.AANode this_lastNode_96 = t_7;
		aatree.AATree.AANode t_9 = obj.nullNode;
		aatree.AATree.AANode left_97 = t_9;
		aatree.AATree.AANode this_nullNode_320 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_324 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_327 = obj.nullNode;
		aatree.AATree.AANode left_70 = this_nullNode_320;
		aatree.AATree.AANode left_83 = this_nullNode_324;
		aatree.AATree.AANode right_84 = this_nullNode_327;
		aatree.AATree.AANode left_465 = obj.nullNode;
		aatree.AATree.AANode right_464 = obj.nullNode;
		int x = 1;
		int x_8 = 1;
		int x_1 = 1;
		int level1_317 = 1;
		int level_20 = 2;
		int x_4 = 1;
		int x_2 = 1;
		int minE_21 = -3;
		int maxE_23 = 3;
		int level1_321 = 1;
		int element_17 = -1;
		int element_463 = -2;
		int d_16 = 0;
		int element_69 = 0;
		int element_316 = -1;
		int element_319 = 0;
		int element_318 = -1;
		int x_6 = 1;
		int level1_22 = 1;
		int a_13 = 0;
		int element_323 = 2;
		int element_82 = 2;
		int element_322 = 0;
		int element_325 = 2;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_17;
		obj.root.left = left_18;
		obj.root.right = right_19;
		obj.root.level = level_20;
		right_19.element = element_69;
		right_19.left = left_70;
		right_19.right = right_71;
		right_19.level = level1_317;
		right_71.element = element_82;
		right_71.left = left_83;
		right_71.right = right_84;
		right_71.level = level1_321;
		left_18.element = element_463;
		left_18.left = left_465;
		left_18.right = right_464;
		left_18.level = level1_22;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove5() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode right_18 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_13 = obj.nullNode;
		aatree.AATree.AANode c_14 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_41 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_42 = t_3;
		aatree.AATree.AANode this_deletedNode_43 = t_3;
		aatree.AATree.AANode t_5 = right_18;
		aatree.AATree.AANode this_lastNode_44 = t_5;
		aatree.AATree.AANode this_lastNode_45 = t_5;
		aatree.AATree.AANode this_lastNode_46 = t_5;
		aatree.AATree.AANode this_lastNode_47 = t_5;
		aatree.AATree.AANode this_lastNode_48 = t_5;
		aatree.AATree.AANode this_lastNode_49 = t_5;
		aatree.AATree.AANode this_lastNode_50 = t_5;
		aatree.AATree.AANode this_nullNode_320 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_323 = obj.nullNode;
		aatree.AATree.AANode left_17 = obj.nullNode;
		aatree.AATree.AANode left_35 = this_nullNode_320;
		aatree.AATree.AANode right_36 = this_nullNode_323;
		int level_19 = 1;
		int x_1 = -1;
		int maxE_22 = 1;
		int d_15 = 0;
		int level_317 = 1;
		int x_4 = -1;
		int x_2 = -1;
		int a_12 = 0;
		int element_34 = 0;
		int element_16 = -1;
		int element_321 = 0;
		int element_318 = -1;
		int element_316 = -1;
		int x = -1;
		int element_319 = 0;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_16;
		obj.root.left = left_17;
		obj.root.right = right_18;
		obj.root.level = level_19;
		right_18.element = element_34;
		right_18.left = left_35;
		right_18.right = right_36;
		right_18.level = level_317;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove6() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode left_26 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_27 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_22 = obj.nullNode;
		aatree.AATree.AANode c_23 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_66 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_67 = t_3;
		aatree.AATree.AANode t_5 = left_26;
		aatree.AATree.AANode this_lastNode_68 = t_5;
		aatree.AATree.AANode this_deletedNode_69 = t_5;
		aatree.AATree.AANode t_7 = obj.nullNode;
		aatree.AATree.AANode right_70 = t_7;
		aatree.AATree.AANode this_nullNode_319 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_323 = obj.nullNode;
		aatree.AATree.AANode left_56 = this_nullNode_319;
		aatree.AATree.AANode right_57 = this_nullNode_323;
		aatree.AATree.AANode left_428 = obj.nullNode;
		aatree.AATree.AANode right_427 = obj.nullNode;
		int minE_29 = -3;
		int x_1 = -1;
		int level1_317 = 1;
		int maxE_31 = 2;
		int element_55 = -2;
		int x_4 = -1;
		int element_320 = -2;
		int x_2 = -1;
		int element_426 = 1;
		int level1_30 = 1;
		int d_24 = 0;
		int element_321 = 0;
		int a_21 = 0;
		int element_318 = -2;
		int level_28 = 2;
		int element_25 = 0;
		int x = -1;
		int x_6 = -1;
		int element_316 = 0;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_25;
		obj.root.left = left_26;
		obj.root.right = right_27;
		obj.root.level = level_28;
		left_26.element = element_55;
		left_26.left = left_56;
		left_26.right = right_57;
		left_26.level = level1_317;
		right_27.element = element_426;
		right_27.left = left_428;
		right_27.right = right_427;
		right_27.level = level1_30;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove7() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode left_18 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_83 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_19 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_14 = obj.nullNode;
		aatree.AATree.AANode c_15 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_100 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_101 = t_3;
		aatree.AATree.AANode t_5 = left_18;
		aatree.AATree.AANode this_lastNode_102 = t_5;
		aatree.AATree.AANode this_deletedNode_103 = t_5;
		aatree.AATree.AANode t_7 = right_83;
		aatree.AATree.AANode this_lastNode_104 = t_7;
		aatree.AATree.AANode t_9 = obj.nullNode;
		aatree.AATree.AANode left_105 = t_9;
		aatree.AATree.AANode this_nullNode_319 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_323 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_327 = obj.nullNode;
		aatree.AATree.AANode left_82 = this_nullNode_319;
		aatree.AATree.AANode left_93 = this_nullNode_323;
		aatree.AATree.AANode right_94 = this_nullNode_327;
		aatree.AATree.AANode left_463 = obj.nullNode;
		aatree.AATree.AANode right_462 = obj.nullNode;
		int x_8 = 1;
		int x_1 = 1;
		int element_92 = 2;
		int level1_317 = 1;
		int level_20 = 2;
		int x_4 = 1;
		int x_2 = 1;
		int minE_21 = -1;
		int maxE_23 = 5;
		int element_17 = 3;
		int element_321 = 0;
		int d_16 = 0;
		int element_318 = 0;
		int x_6 = 1;
		int element_316 = 3;
		int level1_320 = 1;
		int element_81 = 0;
		int level1_22 = 1;
		int a_13 = 0;
		int element_461 = 4;
		int element_324 = 2;
		int element_322 = 2;
		int x = 1;
		int element_325 = 3;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_17;
		obj.root.left = left_18;
		obj.root.right = right_19;
		obj.root.level = level_20;
		left_18.element = element_81;
		left_18.left = left_82;
		left_18.right = right_83;
		left_18.level = level1_317;
		right_83.element = element_92;
		right_83.left = left_93;
		right_83.right = right_94;
		right_83.level = level1_320;
		right_19.element = element_461;
		right_19.left = left_463;
		right_19.right = right_462;
		right_19.level = level1_22;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove8() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode b_10 = obj.nullNode;
		aatree.AATree.AANode c_11 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_25 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_26 = t_3;
		aatree.AATree.AANode this_deletedNode_27 = t_3;
		aatree.AATree.AANode t_5 = obj.nullNode;
		aatree.AATree.AANode right_28 = t_5;
		aatree.AATree.AANode this_nullNode_319 = obj.nullNode;
		aatree.AATree.AANode left_14 = obj.nullNode;
		aatree.AATree.AANode right_15 = this_nullNode_319;
		int level_16 = 1;
		int x_1 = 0;
		int x_2 = 0;
		int element_316 = -1;
		int a_9 = 0;
		int element_317 = -1;
		int element_13 = -1;
		int d_12 = 0;
		int x_4 = 0;
		int x = 0;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_13;
		obj.root.left = left_14;
		obj.root.right = right_15;
		obj.root.level = level_16;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove9() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode left_18 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_86 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_19 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_14 = obj.nullNode;
		aatree.AATree.AANode c_15 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_103 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_104 = t_3;
		aatree.AATree.AANode t_5 = left_18;
		aatree.AATree.AANode this_lastNode_105 = t_5;
		aatree.AATree.AANode this_deletedNode_106 = t_5;
		aatree.AATree.AANode t_7 = right_86;
		aatree.AATree.AANode this_lastNode_107 = t_7;
		aatree.AATree.AANode this_deletedNode_108 = t_7;
		aatree.AATree.AANode t_9 = obj.nullNode;
		aatree.AATree.AANode right_109 = t_9;
		aatree.AATree.AANode this_nullNode_319 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_323 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_327 = obj.nullNode;
		aatree.AATree.AANode left_85 = this_nullNode_319;
		aatree.AATree.AANode left_96 = this_nullNode_323;
		aatree.AATree.AANode right_97 = this_nullNode_327;
		aatree.AATree.AANode left_465 = obj.nullNode;
		aatree.AATree.AANode right_464 = obj.nullNode;
		int x_8 = -1;
		int x_1 = -1;
		int level1_317 = 1;
		int level_20 = 2;
		int x_4 = -1;
		int x_2 = -1;
		int minE_21 = -4;
		int maxE_23 = 2;
		int element_17 = 0;
		int element_84 = -3;
		int element_321 = -3;
		int element_463 = 1;
		int d_16 = 0;
		int element_318 = -3;
		int x_6 = -1;
		int element_316 = 0;
		int level1_320 = 1;
		int level1_22 = 1;
		int a_13 = 0;
		int element_95 = -2;
		int element_322 = -2;
		int element_324 = -2;
		int x = -1;
		int element_325 = 0;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_17;
		obj.root.left = left_18;
		obj.root.right = right_19;
		obj.root.level = level_20;
		left_18.element = element_84;
		left_18.left = left_85;
		left_18.right = right_86;
		left_18.level = level1_317;
		right_86.element = element_95;
		right_86.left = left_96;
		right_86.right = right_97;
		right_86.level = level1_320;
		right_19.element = element_463;
		right_19.left = left_465;
		right_19.right = right_464;
		right_19.level = level1_22;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove10() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode right_16 = new aatree.AATree.AANode();
		aatree.AATree.AANode left_15 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_126 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_11 = obj.nullNode;
		aatree.AATree.AANode c_12 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_136 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_137 = t_3;
		aatree.AATree.AANode this_deletedNode_138 = t_3;
		aatree.AATree.AANode t_5 = right_16;
		aatree.AATree.AANode this_lastNode_139 = t_5;
		aatree.AATree.AANode this_deletedNode_140 = t_5;
		aatree.AATree.AANode t_7 = obj.nullNode;
		aatree.AATree.AANode right_141 = t_7;
		aatree.AATree.AANode t_8 = right_141;
		aatree.AATree.AANode right_143 = t_8;
		aatree.AATree.AANode this_nullNode_320 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_323 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_327 = obj.nullNode;
		aatree.AATree.AANode left_74 = obj.nullNode;
		aatree.AATree.AANode right_75 = this_nullNode_320;
		aatree.AATree.AANode left_125 = this_nullNode_323;
		aatree.AATree.AANode left_488 = this_nullNode_327;
		aatree.AATree.AANode right_487 = this_nullNode_327;
		int x_1 = 1;
		int x_4 = 1;
		int x_2 = 1;
		int element_124 = -2;
		int level1_321 = 1;
		int level_17 = 2;
		int element_318 = 1;
		int element_316 = 0;
		int x_6 = 1;
		int element_486 = -1;
		int d_13 = 0;
		int minE_18 = -3;
		int level1_19 = 1;
		int a_10 = 0;
		int element_14 = 0;
		int element_317 = 1;
		int level1_326 = 1;
		int element_142 = 1;
		int element_73 = 1;
		int element_322 = -2;
		int element_324 = -2;
		int maxE_20 = 2;
		int x = 1;
		int element_325 = 0;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_14;
		obj.root.left = left_15;
		obj.root.right = right_16;
		obj.root.level = level_17;
		right_16.element = element_73;
		right_16.left = left_74;
		right_16.right = right_75;
		right_16.level = level1_19;
		left_15.element = element_124;
		left_15.left = left_125;
		left_15.right = right_126;
		left_15.level = level1_321;
		right_126.element = element_486;
		right_126.left = left_488;
		right_126.right = right_487;
		right_126.level = level1_326;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove11() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode b_11 = obj.nullNode;
		aatree.AATree.AANode c_12 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_33 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_34 = t_3;
		aatree.AATree.AANode this_deletedNode_35 = t_3;
		aatree.AATree.AANode this_deletedNode_36 = t_3;
		aatree.AATree.AANode this_deletedNode_37 = t_3;
		aatree.AATree.AANode this_deletedNode_38 = t_3;
		aatree.AATree.AANode this_deletedNode_39 = t_3;
		aatree.AATree.AANode this_deletedNode_40 = t_3;
		aatree.AATree.AANode this_deletedNode_41 = t_3;
		aatree.AATree.AANode this_deletedNode_42 = t_3;
		aatree.AATree.AANode this_deletedNode_43 = t_3;
		aatree.AATree.AANode t_5 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_319 = obj.nullNode;
		aatree.AATree.AANode left_15 = obj.nullNode;
		aatree.AATree.AANode right_16 = this_nullNode_319;
		int element_316 = 0;
		int x_1 = 0;
		int d_13 = 0;
		int a_10 = 0;
		int element_14 = 0;
		int x_4 = 0;
		int x_2 = 0;
		int element_317 = 0;
		int level_17 = 1;
		int x = 0;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_14;
		obj.root.left = left_15;
		obj.root.right = right_16;
		obj.root.level = level_17;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove12() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode right_19 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_73 = new aatree.AATree.AANode();
		aatree.AATree.AANode left_18 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_14 = obj.nullNode;
		aatree.AATree.AANode c_15 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_93 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_94 = t_3;
		aatree.AATree.AANode this_deletedNode_95 = t_3;
		aatree.AATree.AANode t_5 = right_19;
		aatree.AATree.AANode this_lastNode_96 = t_5;
		aatree.AATree.AANode this_deletedNode_97 = t_5;
		aatree.AATree.AANode t_7 = right_73;
		aatree.AATree.AANode this_lastNode_98 = t_7;
		aatree.AATree.AANode this_deletedNode_99 = t_7;
		aatree.AATree.AANode t_9 = obj.nullNode;
		aatree.AATree.AANode right_100 = t_9;
		aatree.AATree.AANode this_nullNode_320 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_324 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_327 = obj.nullNode;
		aatree.AATree.AANode left_72 = this_nullNode_320;
		aatree.AATree.AANode left_85 = this_nullNode_324;
		aatree.AATree.AANode right_86 = this_nullNode_327;
		aatree.AATree.AANode left_467 = obj.nullNode;
		aatree.AATree.AANode right_466 = obj.nullNode;
		int element_325 = 1;
		int x_1 = 2;
		int level1_317 = 1;
		int element_71 = 0;
		int level_20 = 2;
		int x_4 = 2;
		int x_2 = 2;
		int minE_21 = -3;
		int maxE_23 = 2;
		int level1_321 = 1;
		int element_17 = -1;
		int element_84 = 1;
		int element_465 = -2;
		int d_16 = 0;
		int element_318 = -1;
		int element_316 = -1;
		int element_319 = 0;
		int x_6 = 2;
		int level1_22 = 1;
		int a_13 = 0;
		int element_323 = 1;
		int element_322 = 0;
		int x = 2;
		int x_8 = 2;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_17;
		obj.root.left = left_18;
		obj.root.right = right_19;
		obj.root.level = level_20;
		right_19.element = element_71;
		right_19.left = left_72;
		right_19.right = right_73;
		right_19.level = level1_317;
		right_73.element = element_84;
		right_73.left = left_85;
		right_73.right = right_86;
		right_73.level = level1_321;
		left_18.element = element_465;
		left_18.left = left_467;
		left_18.right = right_466;
		left_18.level = level1_22;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove13() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode left_15 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_16 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_46 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_11 = obj.nullNode;
		aatree.AATree.AANode c_12 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_50 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_51 = t_3;
		aatree.AATree.AANode t_5 = left_15;
		aatree.AATree.AANode this_lastNode_52 = t_5;
		aatree.AATree.AANode this_deletedNode_53 = t_5;
		aatree.AATree.AANode t_7 = right_46;
		aatree.AATree.AANode this_deletedNode_54 = t_5;
		aatree.AATree.AANode this_nullNode_319 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_323 = obj.nullNode;
		aatree.AATree.AANode left_45 = this_nullNode_319;
		aatree.AATree.AANode left_426 = obj.nullNode;
		aatree.AATree.AANode right_425 = obj.nullNode;
		aatree.AATree.AANode left_438 = this_nullNode_323;
		aatree.AATree.AANode right_437 = this_nullNode_323;
		int x_1 = -1;
		int level1_317 = 1;
		int d_13 = 0;
		int minE_18 = -3;
		int level1_19 = 1;
		int a_10 = 0;
		int x_4 = -1;
		int level1_322 = 1;
		int element_14 = 0;
		int element_320 = -2;
		int element_44 = -2;
		int x_2 = -1;
		int element_436 = -1;
		int level_17 = 2;
		int element_318 = -2;
		int element_321 = 0;
		int element_424 = 1;
		int x_6 = -1;
		int x = -1;
		int element_316 = 0;
		int maxE_20 = 2;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_14;
		obj.root.left = left_15;
		obj.root.right = right_16;
		obj.root.level = level_17;
		left_15.element = element_44;
		left_15.left = left_45;
		left_15.right = right_46;
		left_15.level = level1_317;
		right_16.element = element_424;
		right_16.left = left_426;
		right_16.right = right_425;
		right_16.level = level1_19;
		right_46.element = element_436;
		right_46.left = left_438;
		right_46.right = right_437;
		right_46.level = level1_322;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove14() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode right_7 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_2 = obj.nullNode;
		aatree.AATree.AANode c_3 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_319 = obj.nullNode;
		aatree.AATree.AANode left_6 = obj.nullNode;
		aatree.AATree.AANode left_368 = this_nullNode_319;
		aatree.AATree.AANode right_367 = this_nullNode_319;
		int level_8 = 1;
		int d_4 = 0;
		int level_318 = 1;
		int element_317 = -1;
		int a_1 = 0;
		int element_5 = -1;
		int maxE_11 = 1;
		int element_316 = -1;
		int element_366 = 0;
		obj.lastNode = null;
		obj.deletedNode = null;
		int x = 0;
		obj.root.element = element_5;
		obj.root.left = left_6;
		obj.root.right = right_7;
		obj.root.level = level_8;
		right_7.element = element_366;
		right_7.left = left_368;
		right_7.right = right_367;
		right_7.level = level_318;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove15() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode left_17 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_18 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_13 = obj.nullNode;
		aatree.AATree.AANode c_14 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_76 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_77 = t_3;
		aatree.AATree.AANode t_5 = left_17;
		aatree.AATree.AANode this_lastNode_78 = t_5;
		aatree.AATree.AANode this_lastNode_79 = t_5;
		aatree.AATree.AANode this_lastNode_80 = t_5;
		aatree.AATree.AANode this_lastNode_81 = t_5;
		aatree.AATree.AANode this_lastNode_82 = t_5;
		aatree.AATree.AANode this_lastNode_83 = t_5;
		aatree.AATree.AANode this_nullNode_319 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_323 = obj.nullNode;
		aatree.AATree.AANode left_63 = this_nullNode_319;
		aatree.AATree.AANode right_64 = this_nullNode_323;
		aatree.AATree.AANode left_422 = obj.nullNode;
		aatree.AATree.AANode right_421 = obj.nullNode;
		int level1_21 = 1;
		int level_19 = 2;
		int x_1 = -1;
		int level1_317 = 1;
		int element_420 = 2;
		int d_15 = 0;
		int maxE_22 = 3;
		int x_4 = -1;
		int element_320 = 0;
		int x_2 = -1;
		int minE_20 = -1;
		int element_62 = 0;
		int a_12 = 0;
		int element_16 = 1;
		int element_321 = 1;
		int element_318 = 0;
		int x = -1;
		int element_316 = 1;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_16;
		obj.root.left = left_17;
		obj.root.right = right_18;
		obj.root.level = level_19;
		left_17.element = element_62;
		left_17.left = left_63;
		left_17.right = right_64;
		left_17.level = level1_317;
		right_18.element = element_420;
		right_18.left = left_422;
		right_18.right = right_421;
		right_18.level = level1_21;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove16() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode left_13 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_14 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_9 = obj.nullNode;
		aatree.AATree.AANode c_10 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_22 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_23 = t_3;
		aatree.AATree.AANode t_5 = left_13;
		aatree.AATree.AANode this_nullNode_319 = obj.nullNode;
		aatree.AATree.AANode left_383 = obj.nullNode;
		aatree.AATree.AANode right_382 = obj.nullNode;
		aatree.AATree.AANode left_391 = this_nullNode_319;
		aatree.AATree.AANode right_390 = this_nullNode_319;
		int x_1 = -1;
		int element_389 = 1;
		int level1_17 = 1;
		int element_12 = 0;
		int x_4 = -1;
		int d_11 = 0;
		int level_15 = 2;
		int element_381 = -1;
		int x_2 = -1;
		int element_317 = 0;
		int minE_16 = -2;
		int maxE_18 = 2;
		int level1_318 = 1;
		int element_316 = 0;
		int a_8 = 0;
		int x = -1;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_12;
		obj.root.left = left_13;
		obj.root.right = right_14;
		obj.root.level = level_15;
		left_13.element = element_381;
		left_13.left = left_383;
		left_13.right = right_382;
		left_13.level = level1_17;
		right_14.element = element_389;
		right_14.left = left_391;
		right_14.right = right_390;
		right_14.level = level1_318;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove17() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode b_2 = obj.nullNode;
		aatree.AATree.AANode c_3 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_319 = obj.nullNode;
		aatree.AATree.AANode left_6 = obj.nullNode;
		aatree.AATree.AANode right_7 = this_nullNode_319;
		int level_8 = 1;
		int d_4 = 0;
		int element_317 = 4;
		int element_5 = 4;
		int a_1 = 0;
		int element_316 = 4;
		obj.lastNode = null;
		obj.deletedNode = null;
		int x = 0;
		obj.root.element = element_5;
		obj.root.left = left_6;
		obj.root.right = right_7;
		obj.root.level = level_8;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove18() throws Exception {
		AATree obj = new AATree();
		obj.root = obj.nullNode;
		aatree.AATree.AANode b_2 = obj.nullNode;
		aatree.AATree.AANode c_3 = obj.nullNode;
		int d_4 = 0;
		int a_1 = 0;
		obj.lastNode = null;
		int x = 0;
		obj.deletedNode = null;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove19() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode right_16 = new aatree.AATree.AANode();
		aatree.AATree.AANode left_15 = new aatree.AATree.AANode();
		aatree.AATree.AANode right_46 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_11 = obj.nullNode;
		aatree.AATree.AANode c_12 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_51 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_52 = t_3;
		aatree.AATree.AANode this_deletedNode_53 = t_3;
		aatree.AATree.AANode t_5 = right_16;
		aatree.AATree.AANode this_lastNode_54 = t_5;
		aatree.AATree.AANode this_deletedNode_55 = t_5;
		aatree.AATree.AANode t_7 = right_46;
		aatree.AATree.AANode this_deletedNode_56 = t_5;
		aatree.AATree.AANode this_deletedNode_57 = t_5;
		aatree.AATree.AANode this_nullNode_320 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_323 = obj.nullNode;
		aatree.AATree.AANode left_45 = this_nullNode_320;
		aatree.AATree.AANode left_434 = obj.nullNode;
		aatree.AATree.AANode right_433 = obj.nullNode;
		aatree.AATree.AANode left_446 = this_nullNode_323;
		aatree.AATree.AANode right_445 = this_nullNode_323;
		int element_319 = 0;
		int x_1 = 0;
		int element_444 = 1;
		int level1_317 = 1;
		int d_13 = 0;
		int minE_18 = -3;
		int level1_322 = 1;
		int level1_19 = 1;
		int x_4 = 0;
		int a_10 = 0;
		int element_14 = -1;
		int element_44 = 0;
		int x_2 = 0;
		int element_432 = -2;
		int level_17 = 2;
		int element_321 = 0;
		int element_318 = -1;
		int maxE_20 = 2;
		int x = 0;
		int x_6 = 0;
		int element_316 = -1;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_14;
		obj.root.left = left_15;
		obj.root.right = right_16;
		obj.root.level = level_17;
		right_16.element = element_44;
		right_16.left = left_45;
		right_16.right = right_46;
		right_16.level = level1_317;
		left_15.element = element_432;
		left_15.left = left_434;
		left_15.right = right_433;
		left_15.level = level1_19;
		right_46.element = element_444;
		right_46.left = left_446;
		right_46.right = right_445;
		right_46.level = level1_322;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

	@Test
	public void test_remove20() throws Exception {
		AATree obj = new AATree();
		obj.root = new aatree.AATree.AANode();
		aatree.AATree.AANode right_17 = new aatree.AATree.AANode();
		aatree.AATree.AANode b_12 = obj.nullNode;
		aatree.AATree.AANode c_13 = obj.nullNode;
		aatree.AATree.AANode this_deletedNode_34 = obj.nullNode;
		aatree.AATree.AANode t_3 = obj.root;
		aatree.AATree.AANode this_lastNode_35 = t_3;
		aatree.AATree.AANode this_deletedNode_36 = t_3;
		aatree.AATree.AANode t_5 = right_17;
		aatree.AATree.AANode this_lastNode_37 = t_5;
		aatree.AATree.AANode t_7 = obj.nullNode;
		aatree.AATree.AANode left_38 = t_7;
		aatree.AATree.AANode this_nullNode_320 = obj.nullNode;
		aatree.AATree.AANode this_nullNode_323 = obj.nullNode;
		aatree.AATree.AANode left_16 = obj.nullNode;
		aatree.AATree.AANode left_28 = this_nullNode_320;
		aatree.AATree.AANode right_29 = this_nullNode_323;
		int element_316 = -2;
		int element_319 = 0;
		int x_1 = -1;
		int level_18 = 1;
		int level_317 = 1;
		int x_4 = -1;
		int a_11 = 0;
		int x_2 = -1;
		int maxE_21 = 1;
		int element_15 = -2;
		int element_27 = 0;
		int element_321 = 0;
		int element_318 = -2;
		int x_6 = -1;
		int x = -1;
		int d_14 = 0;
		obj.lastNode = null;
		obj.deletedNode = null;
		obj.root.element = element_15;
		obj.root.left = left_16;
		obj.root.right = right_17;
		obj.root.level = level_18;
		right_17.element = element_27;
		right_17.left = left_28;
		right_17.right = right_29;
		right_17.level = level_317;
		//System.out.println(Utilities.repOK(obj));
		obj.remove(x);
	}

}

